language: node_js

dist: xenial

os: linux

node_js:
  - "16"

install:
  - npm install
  - npm run build

deploy:
  strategy: git
  local_dir: dist
  provider: pages
  cleanup: false
  token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  on:
    branch: master

script: echo "done"