language: node_js

dist: xenial

os: linux

node_js:
  - "16"

install:
  - npm install
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master

script: echo "done"